### ISSUE TITLE
Allow PHP 8?

### ISSUE THREAD

**Issue by pedro-stanaka** [repman-io/composer-plugin#11]
I dont see from composer side any impediment on using `php` version constraint as `>= 7.2.0`.

Can we allow install from PHP 8? I can submit PR, if you guys are too busy :wink:

**Comment by akondas** [comment]
There are no contraindications. We can allow for PHP 8 :wink:

**Comment by pedro-stanaka** [comment]
@akondas can we tag this change pls? I just tried once again to install some deps with PHP 8 and it was not possible because composer does not see newer tag than 1.0.0. Thx!

**Comment by akondas** [comment]
Sorry for the delay and thanks for the help:
https://github.com/repman-io/composer-plugin/releases/tag/1.1.0
