### ISSUE TITLE
Reconsider min php version of 7.3 to at least 7.2

### ISSUE THREAD

**Issue by ProxiBlue** [repman-io/composer-plugin#3]
Granted 7.2 is only on security releases, but a LOT of software still runs on that version, and your min php of 7.3 locks the usage of this package manager out.

example: Still lots of magento commerce 1 and versions of magento 2 that still runs on 7.2

Please consider allowing 7.2

**Comment by akondas** [comment]
It seems to me that if there are no technical obstacles to this, we can do it. Although in my opinion it is better to force update.

**Comment by ProxiBlue** [comment]
> Although in my opinion it is better to force update.

Can't agree more. They paying client(s) have other ideas. ;)

**Comment by akondas** [comment]
So maybe, can we do something to force update instead of downgrading? (just asking :wink: )

**Comment by ProxiBlue** [comment]
Consider a platform like magento ecommerce.
That is not just a simple 'upgrade' - it can cost $$$$

Lots of m1 stores still running, limited to PHP 7.2 (for now)
Lots of older m2 stores up and running, still on 7.2 - again $$$$ to upgrade

Consider the current world economic climate, the chances are poor.

Is not a biggie, just means I won;t be using this repo with some clients, and stick to custom run satis instances.

Figured I'd ask, no harm done in that ;)

**Comment by akondas** [comment]
The release will take place today :wink:

**Comment by akondas** [comment]
https://github.com/repman-io/composer-plugin/releases/tag/0.1.3
